batch_size: 32
n_epochs: 100
n_initial_points: 5
n_iter: 50
num_workers: 4
patience: 20
pin_memory: True
shuffle: True

dataset:
  train:
    XRayDataset:
      d1data: "/lustre04/scratch/jdv/xray/NIH/images-128"
      d1csv: "/lustre04/scratch/jdv/xray/Data_Entry_2017.csv"
      d2data: "/lustre04/scratch/jdv/xray/PC/images-128"
      d2csv: "/lustre04/scratch/jdv/xray/PADCHEST_chest_x_ray_images_labels_160K_01.02.19.csv"
      ratio: 0.5
      mode: "train"
      seed: 1234
  valid:
    XRayDataset:
      d1data: "/lustre04/scratch/jdv/xray/NIH/images-128"
      d1csv: "/lustre04/scratch/jdv/xray/Data_Entry_2017.csv"
      d2data: "/lustre04/scratch/jdv/xray/PC/images-128"
      d2csv: "/lustre04/scratch/jdv/xray/PADCHEST_chest_x_ray_images_labels_160K_01.02.19.csv"
      ratio: 0.5
      mode: "valid"
      seed: 1234
  test:
    XRayDataset:
      d1data: "/lustre04/scratch/jdv/xray/NIH/images-128"
      d1csv: "/lustre04/scratch/jdv/xray/Data_Entry_2017.csv"
      d2data: "/lustre04/scratch/jdv/xray/PC/images-128"
      d2csv: "/lustre04/scratch/jdv/xray/PADCHEST_chest_x_ray_images_labels_160K_01.02.19.csv"
      ratio: 0.5
      mode: "test"
      seed: 1234

optimizer:
  Adam:
    lr: "Real(10**-5, 10**-2, 'log-uniform')"

transform:
        train: {}
        valid: {}
        test: {}
