batch_size: 16
n_epochs: 100
n_initial_points: 5
n_iter: 50
num_workers: 8
patience: 20
pin_memory: True
shuffle: True

dataset:
  train:
    XRayDataset:
      d1data: "/home/cohenjos/projects/def-marzyeh/cohenjos/NIH/images-224"
      d1csv: "/home/cohenjos/projects/def-marzyeh/cohenjos//NIH/Data_Entry_2017.csv"
      d2data: "/home/cohenjos/projects/def-marzyeh/cohenjos/PC/images-224"
      d2csv: "/home/cohenjos/projects/def-marzyeh/cohenjos/PC/PADCHEST_chest_x_ray_images_labels_160K_01.02.19.csv"
      ratio: 0.5
      mode: "train"
  valid:
    XRayDataset:
      d1data: "/home/cohenjos/projects/def-marzyeh/cohenjos/NIH/images-224"
      d1csv: "/home/cohenjos/projects/def-marzyeh/cohenjos/NIH/Data_Entry_2017.csv"
      d2data: "/home/cohenjos/projects/def-marzyeh/cohenjos/PC/images-224"
      d2csv: "/home/cohenjos/projects/def-marzyeh/cohenjos/PC/PADCHEST_chest_x_ray_images_labels_160K_01.02.19.csv"
      ratio: 0.5
      mode: "valid"
  test:
    XRayDataset:
      d1data: "/home/cohenjos/projects/def-marzyeh/cohenjos/NIH/images-224"
      d1csv: "/home/cohenjos/projects/def-marzyeh/cohenjos/NIH/Data_Entry_2017.csv"
      d2data: "/home/cohenjos/projects/def-marzyeh/cohenjos/PC/images-224"
      d2csv: "/home/cohenjos/projects/def-marzyeh/cohenjos/PC/PADCHEST_chest_x_ray_images_labels_160K_01.02.19.csv"
      ratio: 0.5
      mode: "test"

optimizer:
  Adam:
    lr: "Real(10**-5, 10**-2, 'log-uniform')"

transform:
        train: {}
        valid: {}
        test: {}
