device: 0
cuda: True
n_iter: 30
n_epochs: 500
schedule_steps: 10
batch_size: 32
shuffle: True
num_workers: 0
pin_memory: True

dataset:
  train:
    XRayDataset:
      d1data: "/lustre04/scratch/jdv/xray/NIH/images-128"
      d1csv: "/lustre04/scratch/jdv/xray/Data_Entry_2017.csv"
      d2data: "/lustre04/scratch/jdv/xray/PC/images-128"
      d2csv: "/lustre04/scratch/jdv/xray/PADCHEST_chest_x_ray_images_labels_160K_01.02.19.csv"
      ratio: 0.5
      mode: "train"
      seed: 1234
  valid:
    XRayDataset:
      d1data: "/lustre04/scratch/jdv/xray/NIH/images-128"
      d1csv: "/lustre04/scratch/jdv/xray/Data_Entry_2017.csv"
      d2data: "/lustre04/scratch/jdv/xray/PC/images-128"
      d2csv: "/lustre04/scratch/jdv/xray/PADCHEST_chest_x_ray_images_labels_160K_01.02.19.csv"
      ratio: 0.5
      mode: "valid"
      seed: 1234
  test:
    XRayDataset:
      d1data: "/lustre04/scratch/jdv/xray/NIH/images-128"
      d1csv: "/lustre04/scratch/jdv/xray/Data_Entry_2017.csv"
      d2data: "/lustre04/scratch/jdv/xray/PC/images-128"
      d2csv: "/lustre04/scratch/jdv/xray/PADCHEST_chest_x_ray_images_labels_160K_01.02.19.csv"
      ratio: 0.5
      mode: "test"
      seed: 1234

optimizer:
  Adam:
    lr: "Real(10**-4, 10**-2, 'log-uniform')"

transform:
        train: {}
        valid: {}
        test: {}
