# General
cuda: True
nsamples_train: 500
maxmasks_train: 256
#new_size: &new_size 28
recon_masked: False
recon_continuous: False
gradmask_lambda: 0
seed: 0

# Training
n_iter: 30
num_epochs: 500
schedule_steps: 10

# DataLoader
batch_size: 32
shuffle: True

# Dataset
dataset:
  train:
    XRayDataset:
      d1data: "/lustre04/scratch/jdv/xray/NIH/images-128"
      d1csv: "/lustre04/scratch/jdv/xray/Data_Entry_2017.csv"
      d2data: "/lustre04/scratch/jdv/xray/PC/images-128"
      d2csv: "/lustre04/scratch/jdv/xray/PADCHEST_chest_x_ray_images_labels_160K_01.02.19.csv"
      ratio: 0.5
      mode: "train"
      seed: 1234
      new_size: 128
  valid:
    XRayDataset:
      d1data: "/lustre04/scratch/jdv/xray/NIH/images-128"
      d1csv: "/lustre04/scratch/jdv/xray/Data_Entry_2017.csv"
      d2data: "/lustre04/scratch/jdv/xray/PC/images-128"
      d2csv: "/lustre04/scratch/jdv/xray/PADCHEST_chest_x_ray_images_labels_160K_01.02.19.csv"
      ratio: 0.5
      mode: "valid"
      seed: 1234
      new_size: 128
  test:
    XRayDataset:
      d1data: "/lustre04/scratch/jdv/xray/NIH/images-128"
      d1csv: "/lustre04/scratch/jdv/xray/Data_Entry_2017.csv"
      d2data: "/lustre04/scratch/jdv/xray/PC/images-128"
      d2csv: "/lustre04/scratch/jdv/xray/PADCHEST_chest_x_ray_images_labels_160K_01.02.19.csv"
      ratio: 0.5
      mode: "test"
      seed: 1234
      new_size: 128

model:
  ResNetSmall:
    base_size: 4608
    img_size: 128

transform:
        train: {}
        valid: {}
        test: {}
