device: 0
cuda: True
num_epochs: 500
schedule_steps: 10
batch_size: 32
shuffle: True
new_size: &new_size 28
num_workers: 4
pin_memory: True

dataset:
  train:
    XRayDataset:
      d1data: "/lustre04/scratch/cohenjos/NIH/images-128"
      d1csv: "/lustre03/project/6008064/jpcohen/ChestXray-NIHCC/Data_Entry_2017.csv"
      d2data: "/lustre04/scratch/cohenjos/PC/images-128"
      d2csv: "/lustre03/project/6008064/jpcohen/PADCHEST_SJ/labels_csv/PADCHEST_chest_x_ray_images_labels_160K_01.02.19.csv"
      ratio: 0.9
      mode: "train"
      seed: 1234
      new_size: 128
  valid:
    XRayDataset:
      d1data: "/lustre04/scratch/cohenjos/NIH/images-128"
      d1csv: "/lustre03/project/6008064/jpcohen/ChestXray-NIHCC/Data_Entry_2017.csv"
      d2data: "/lustre04/scratch/cohenjos/PC/images-128"
      d2csv: "/lustre03/project/6008064/jpcohen/PADCHEST_SJ/labels_csv/PADCHEST_chest_x_ray_images_labels_160K_01.02.19.csv"
      ratio: 0.9
      mode: "valid"
      seed: 1234
      new_size: 128
  test:
    XRayDataset:
      d1data: "/lustre04/scratch/cohenjos/NIH/images-128"
      d1csv: "/lustre03/project/6008064/jpcohen/ChestXray-NIHCC/Data_Entry_2017.csv"
      d2data: "/lustre04/scratch/cohenjos/PC/images-128"
      d2csv: "/lustre03/project/6008064/jpcohen/PADCHEST_SJ/labels_csv/PADCHEST_chest_x_ray_images_labels_160K_01.02.19.csv"
      ratio: 0.9
      mode: "test"
      seed: 1234
      new_size: 128

optimizer:
  Adam:
    lr: "Real(10**-4, 10**-2, 'log-uniform')"

transform:
        train: {}
        valid: {}
        test: {}