base: "base_xray_balanced.yml"

model:
  ResNet:
    resnet_type: "18"
    actdiff_lamb: "Real(10**-3, 10, 'log-uniform')"
    gradmask_lamb: "Real(10**-3, 10, 'log-uniform')"

dataset:
  train:
    XRayDataset:
        mask_all: True
dataset:
  valid:
    XRayDataset:
        mask_all: True
dataset:
  test:
    XRayDataset:
        mask_all: True
