# General
base: "base_xray_balanced.yml"
bre_lambda: 0
recon_lambda: 0
actdiff_lambda: "Real(10**-3, 10, 'log-uniform')"
gradmask_lambda: 0

# Optimizer
optimizer:
  Adam:
    lr: "Real(10**-4, 10**-2, 'log-uniform')"
