# General
base: "base_xray.yml"

model:
  ResNetModel:
    base_size: 8192
    resnet_type: "18"
    actdiff_lamb: 0
    gradmask_lamb: 0

dataset:
  train:
    XRayDataset:
        mask_all: True
dataset:
  valid:
    XRayDataset:
        mask_all: True
dataset:
  test:
    XRayDataset:
        mask_all: True
