base: "base_cardiacmsd.yml"

dataset:
  train:
    HeartMSDDataset:
      blur: 20

model:
  ResNetModel:
    resnet_type: "18"
    actdiff_lamb: 0
    gradmask_lamb: 0.008388
    disc_lamb: 0
    save_acts: []

optimizer:
  Adam:
    lr: 0.000010
