base: "base_cardiacmsd.yml"

dataset:
  train:
    HeartMSDDataset:
      blur: 2.0

model:
  ResNetModel:
    resnet_type: "18"
    actdiff_lamb: 0
    gradmask_lamb: 0
    disc_lamb: 0
    save_acts: []
    #base_size: 4608


optimizer:
  Adam:
    lr: 0.000052
