base: "base_cardiacmsd.yml"

dataset:
  train:
    HeartMSDDataset:
      blur: 2

model:
  ResNetModel:
    resnet_type: "18"
    actdiff_lamb: 0.000105
    gradmask_lamb: 0
    disc_lamb: 0
    save_acts: [5]


optimizer:
  Adam:
    lr: 0.000100
