# General
cuda: True
penalise_grad: 'False'
n_iter: 30
penalise_grad_lambda_1: "Real(0., 10.)"
penalise_grad_lambda_2: "Real(0., 10.)"
conditional_reg: False
penalise_grad_usemasks: True 
nsamples_train: 800
maxmasks_train: 256
new_size: &new_size 512

# Training
num_epochs: 100

# DataLoader
batch_size: 4
shuffle: True

# Dataset
dataset:
  train:
    LungMSDDataset:
      mode: 'train'
      blur: "Integer(0, 5)"
      new_size: *new_size
  valid:
    LungMSDDataset:
      mode: 'valid'
      nsamples: 256
      new_size: *new_size
  test:
    LungMSDDataset:
      mode: 'test'
      nsamples: 256
      new_size: *new_size

# Model
model:
  UNet2: 
    flat_layer: "Integer(2, 6)"

# Optimizer
optimizer:
  Adam:
    lr: "Real(10**-4, 10**-2, 'log-uniform')"

transform:
        train: {}
        valid: {}
        test: {}

# mlflow experiment manager
manager:
    set_experiment:
        name: 'exploration_2' # Experience name
    set_tracking_uri:
        uri: '' # Link or url to where to store the logs. Default is `./mlruns`
