batch_size: 32
n_epochs: 100
num_workers: 1
pin_memory: True
shuffle: True

dataset:
  train:
    SyntheticDataset:
      mode: 'distractor1'
      blur: 'Integer(2, 10)'
      nsamples: 500
      dataroot: &dataroot "/home/jdv/code/activmask/data/synth2"
      distract_noise: 0
  valid:
    SyntheticDataset:
      mode: 'distractor2'
      nsamples: 128
      dataroot: *dataroot
      distract_noise: 1
  test:
    SyntheticDataset:
      mode: 'distractor3'
      nsamples: 128
      dataroot: *dataroot
      distract_noise: 1

transform:
        train: {}
        valid: {}
        test: {}
