batch_size: 32
n_epochs: 100
num_workers: 4
n_iter: 50
patience: 100
pin_memory: True
shuffle: True

dataset:
  train:
    SyntheticDataset:
      mode: 'distractor1'
      nsamples: 500
      dataroot: &dataroot "/home/cohenjos/workspace/activmask/data/synth_hard"
      distract_noise: 0
  valid:
    SyntheticDataset:
      mode: 'distractor2'
      nsamples: 128
      dataroot: *dataroot
      distract_noise: 1
  test:
    SyntheticDataset:
      mode: 'distractor3'
      nsamples: 128
      dataroot: *dataroot
      distract_noise: 1

transform:
        train: {}
        valid: {}
        test: {}
