base: 'base_synth.yml'

dataset:
  train:
    SyntheticDataset:
      blur: 0.639513

model:
  ResNetModel:
    resnet_type: "18"
    actdiff_lamb: 0
    gradmask_lamb: 0
    disc_lamb: 10.000000
    disc_iter: 10
    disc_lr: 0.010000
    save_acts: [5]


optimizer:
  Adam:
    lr: 0.000371
