base: 'base_synth.yml'

dataset:
  train:
    SyntheticDataset:
      blur: 2

model:
  ResNetModel:
    resnet_type: "18"
    actdiff_lamb: 0
    gradmask_lamb: 0
    disc_lamb: 2.647180
    disc_iter: 3
    disc_lr: 0.000100
    save_acts: [5]


optimizer:
  Adam:
    lr: 0.000022
