base: "base_covid_balanced.yml"

model:
  DenseNetModel:
    actdiff_lamb: 0
    gradmask_lamb: 0
    disc_lamb: 0

dataset:
  train:
    XRayCOVIDDataset:
        mask_all: True
dataset:
  valid:
    XRayCOVIDDataset:
        mask_all: True
dataset:
  test:
    XRayCOVIDDataset:
        mask_all: True
