base: "base_pancreasmsd.yml"

dataset:
  train:
    PancreasMSDDataset:
      blur: 20

model:
  ResNetModel:
    resnet_type: "18"
    actdiff_lamb: 0
    gradmask_lamb: 0
    disc_lamb: 0.017167
    disc_iter: 2
    disc_lr: 0.000328
    save_acts: [5]


optimizer:
  Adam:
    lr: 0.000537
