base: "base_pancreasmsd.yml"

dataset:
  train:
    PancreasMSDDataset:
      blur: 20

model:
  ResNetModel:
    resnet_type: "18"
    actdiff_lamb: 0.001615
    gradmask_lamb: 0
    disc_lamb: 0
    save_acts: [5]


optimizer:
  Adam:
    lr: 0.000053
