base: "base_pancreasmsd.yml"

dataset:
  train:
    PancreasMSDDataset:
      blur: 15
      mask_all: True

model:
  ResNetModel:
    resnet_type: "18"
    actdiff_lamb: 0
    gradmask_lamb: 0
    disc_lamb: 0
    save_acts: []


optimizer:
  Adam:
    lr: 0.000615
