base: "base_pancreasmsd.yml"

dataset:
  train:
    PancreasMSDDataset:
      blur: 2.000000

model:
  ResNetModel:
    resnet_type: "18"
    actdiff_lamb: 0
    gradmask_lamb: 0.003477
    disc_lamb: 0
    save_acts: []


optimizer:
  Adam:
    lr: 0.000106
