# General
cuda: True
n_iter: 30
nsamples_train: 500
maxmasks_train: 256
new_size: &new_size 28
recon_masked: False
recon_continuous: False
gradmask_lambda: 0

# Training
num_epochs: 100
schedule_steps: 10

# DataLoader
batch_size: 128
shuffle: True

# Dataset
dataset:
  train:
    SyntheticDataset:
      mode: 'distractor1'
      blur: 2
      nsamples: 500
      new_size: *new_size
      dataroot: &dataroot './data/synth2/'
      distract_noise: 0
  valid:
    SyntheticDataset:
      mode: 'distractor2'
      blur: 2
      nsamples: 128
      new_size: *new_size
      dataroot: *dataroot
      distract_noise: 1
  test:
    SyntheticDataset:
      mode: 'distractor3'
      blur: 2
      nsamples: 128
      new_size: *new_size
      dataroot: *dataroot
      distract_noise: 1

transform:
        train: {}
        valid: {}
        test: {}
