# General
cuda: True
penalise_grad: 'diff_from_ref'
n_iter: 30
penalise_grad_lambda_1: "Real(0., 10.)"
penalise_grad_lambda_2: "Real(0., 10.)"
conditional_reg: False
penalise_grad_usemasks: True 
nsamples_train: 64
maxmasks_train: 256

# Training
num_epochs: 100

# DataLoader
batch_size: 32
shuffle: True

# Dataset
dataset:
  train:
    LiverMSDDataset:
      mode: 'train'
      blur: "Integer(0, 5)"
  valid:
    LiverMSDDataset:
      mode: 'valid'
      nsamples: 256
  test:
    LiverMSDDataset:
      mode: 'test'
      nsamples: 256

# Model
model:
  SimpleCNN: 
    flat_layer: "Integer(2, 6)"

# Optimizer
optimizer:
  Adam:
    lr: "Real(10**-4, 10**-2, 'log-uniform')"

transform:
        train: {}
        valid: {}
        test: {}

# mlflow experiment manager
manager:
    set_experiment:
        name: 'exploration_2' # Experience name
    set_tracking_uri:
        uri: '' # Link or url to where to store the logs. Default is `./mlruns`
