# General
cuda: True
penalise_grad: 'diff_from_ref'
n_iter: 30
penalise_grad_lambda_1: 1
penalise_grad_lambda_2: 1
conditional_reg: False
penalise_grad_usemasks: True 
nsamples_train: 64
maxmasks_train: 256

# Training
num_epochs: 200

# DataLoader
batch_size: 2
shuffle: True

# Dataset
dataset:
  train:
    LiverMSDDataset:
      mode: 'train'
      blur: 7
      new_size: 512
  valid:
    LiverMSDDataset:
      mode: 'valid'
      nsamples: 128
      blur: 7
      new_size: 512
  test:
    LiverMSDDataset:
      mode: 'test'
      nsamples: 128
      new_size: 512

# Model
model:
  SimpleCNN: 
    flat_layer: 200

# Optimizer
optimizer:
  Adam:
    lr: 0.0001

transform:
        train: {}
        valid: {}
        test: {}

