# General
seed: 1234
cuda: True
nsamples: 64
maxmasks: 256
penalise_grad: 'diff_from_ref'
blur: 0

# Training
num_epochs: 500

# DataLoader
batch_size: 32
shuffle: True

# Dataset
dataset:
  train:
    LungMSDDataset:
      mode: 'train'
  valid:
    LungMSDDataset:
      mode: 'valid'
  test:
    LungMSDDataset:
      mode: 'test'

# Model
model:
  SimpleCNN: 
    flat_layer: 200

# Optimizer
optimizer:
  SGD:
    lr: 0.00031116518486790096

transform:
        train: {}
        valid: {}
        test: {}
