# General
cuda: True
penalise_grad: 'False'
n_iter: 30
penalise_grad_lambda_1: 1
penalise_grad_lambda_2: 1
conditional_reg: False
penalise_grad_usemasks: True 
nsamples_train: 800
maxmasks_train: 256
new_size: &new_size 512

# Training
num_epochs: 200

# DataLoader
batch_size: 2
shuffle: True

# Dataset
dataset:
  train:
    LungMSDDataset:
      mode: 'train'
      blur: 7
      new_size: *new_size
  valid:
    LungMSDDataset:
      mode: 'valid'
      nsamples: 128
      blur: 7
      new_size: *new_size
  test:
    LungMSDDataset:
      mode: 'test'
      nsamples: 128
      new_size: *new_size

# Model
model:
  UNet2: 
    flat_layer: 200

# Optimizer
optimizer:
  Adam:
    lr: 0.0001

transform:
        train: {}
        valid: {}
        test: {}

