# General
seed: &seed 1234
cuda: True
nsamples: &nsamples 64
penalise_grad: 'contrast'
penalise_grad_lambda_1: "Real(0., 10.)"
penalise_grad_lambda_2: "Real(0., 10.)"

# Training
num_epochs: 100

# DataLoader
batch_size: 32
shuffle: True

# Dataset
dataset:
  train:
    LungMSDDataset:
      mode: 'train'
      seed: *seed
      nsamples: *nsamples
      maxmasks: &maxmasks "Integer(0, 64)"
      blur: &blur "Integer(0, 10)"
  valid:
    LungMSDDataset:
      mode: 'valid'
      seed: *seed
      nsamples: *nsamples
      maxmasks: *maxmasks
      blur: *blur
  test:
    LungMSDDataset:
      mode: 'test'
      seed: *seed
      nsamples: *nsamples
      maxmasks: *maxmasks
      blur: *blur

# Model
model:
  SimpleCNN: 
    flat_layer: 200

# Optimizer
optimizer:
  SGD:
    lr: "Real(10**-5, 10**-2, 'log-uniform')"

transform:
        train: {}
        valid: {}
        test: {}

# mlflow experiment manager
manager:
    set_experiment:
        name: 'exploration_1' # Experience name
    set_tracking_uri:
        uri: '' # Link or url to where to store the logs. Default is `./mlruns`
