# General
conditional_reg: True
penalise_grad_usemasks: True
cuda: True
nsamples: &nsamples 64
maxmasks: &maxmasks 8
penalise_grad: 'contrast'
blur: &blur 0

# Training
num_epochs: 200

# DataLoader
batch_size: 32
shuffle: True

# Dataset
dataset:
  train:
    LungMSDDataset:
      mode: 'train'
      maxmasks: *maxmasks
  valid:
    LungMSDDataset:
      mode: 'valid'
      seed: *seed
      nsamples: 256
      maxmasks: *maxmasks
  test:
    LungMSDDataset:
      mode: 'test'
      seed: *seed
      nsamples: 256
      maxmasks: *maxmasks

# Model
model:
  SimpleCNN: 
    flat_layer: 200

# Optimizer
optimizer:
  SGD:
    lr: 0.00031116518486790096

transform:
        train: {}
        valid: {}
        test: {}

# mlflow experiment manager
manager:
    set_experiment:
        name: 'testing123' # Experience name
    set_tracking_uri:
        uri: '' # Link or url to where to store the logs. Default is `./mlruns`
