# General
cuda: True
penalise_grad: 'False'
n_iter: 30
penalise_grad_lambda_1: 1
penalise_grad_lambda_2: 1
conditional_reg: False
penalise_grad_usemasks: True 
nsamples_train: 128
maxmasks_train: 256
new_size: &new_size 512

# Training
num_epochs: 50

# DataLoader
batch_size: 32
shuffle: True

# Dataset
dataset:
  train:
    SyntheticDataset:
      mode: 'distractor1'
      blur: 1
#      nsamples: 32
      new_size: *new_size
      dataroot: &dataroot './data/synth2/'
      distract_noise: 0.0
  valid:
    SyntheticDataset:
      mode: 'distractor2'
      nsamples: 128
      blur: 1
      distract_noise: 1.0
      new_size: *new_size
      dataroot: *dataroot
  test:
    SyntheticDataset:
      mode: 'distractor3'
      nsamples: 128
      new_size: *new_size
      dataroot: *dataroot

# Model
model:
  ResNetSmall: 
    flat_layer: 2
    img_size: 28

# Optimizer
optimizer:
  Adam:
    lr: 0.0001

transform:
        train: {}
        valid: {}
        test: {}

