# General
cuda: False
n_iter: 30
penalise_grad: 'contrast'
penalise_grad_lambda_1: 1
penalise_grad_lambda_2: 1
penalise_grad_usemasks: True
conditional_reg: False
nsamples_train: 500
maxmasks_train: 256
new_size: &new_size 512

# Training
num_epochs: 50

# DataLoader
batch_size: 32
shuffle: True

# Dataset
dataset:
  train:
    SyntheticDataset:
      mode: 'train'
      blur: 0.4
      new_size: *new_size
      dataroot: &dataroot './data/synth/'
      distract_noise: 0.5
  valid:
    SyntheticDataset:
      mode: 'valid'
      nsamples: 128
      blur: 0.4
      new_size: *new_size
      dataroot: *dataroot
  test:
    SyntheticDataset:
      mode: 'test'
      nsamples: 128
      new_size: *new_size
      dataroot: *dataroot

# Model
model:
  SimpleCNN:
    flat_layer: 2

# Optimizer
optimizer:
  Adam:
    lr: 0.00001 # 0.00001

transform:
        train: {}
        valid: {}
        test: {}

