# General
cuda: True
n_iter: 200
penalise_grad: 'contrast'
gradmask_lambda: 1
bre_lambda: 2
penalise_grad_usemasks: True
conditional_reg: False
nsamples_train: 500
maxmasks_train: 256
new_size: &new_size 28

# Training
num_epochs: 50

# DataLoader
batch_size: 32
shuffle: True

# Dataset
dataset:
  train:
    SyntheticDataset:
      mode: 'train'
      blur: 10
      nsamples: 500
      new_size: *new_size
      dataroot: &dataroot './data/synth/'
      distract_noise: 0
  valid:
    SyntheticDataset:
      mode: 'train_flip'
      nsamples: 128
      blur: 10
      new_size: *new_size
      dataroot: *dataroot
  test:
    SyntheticDataset:
      mode: 'test'
      nsamples: 128
      new_size: *new_size
      dataroot: *dataroot

# Model
model:
  SimpleCNN:
    flat_layer: 2
    img_size: 28

# Optimizer
optimizer:
  Adam:
    lr:  0.001 # 0.0001

transform:
        train: {}
        valid: {}
        test: {}

