batch_size: 32
cuda: True
device: 0
n_iter: 30
n_epochs: 500
num_workers: 0
pin_memory: True
schedule_steps: 10
shuffle: True

dataset:
  train:
    LiverMSDDataset:
      mode: 'train'
      blur: 'Integer(2, 40)'
      nsamples: 128
  valid:
    LiverMSDDataset:
      mode: 'valid'
      nsamples: 256
  test:
    LiverMSDDataset:
      mode: 'test'
      nsamples: 256

optimizer:
  Adam:
    lr: "Real(10**-4, 10**-2, 'log-uniform')"

transform:
        train: {}
        valid: {}
        test: {}
