# General
cuda: True
nsamples_train: 128
maxmasks_train: 256
recon_masked: False
recon_continuous: True
gradmask_lambda: 0

# Training
num_epochs: 100
schedule_steps: 10

# DataLoader
batch_size: 32
shuffle: True

# Dataset
dataset:
  train:
    LiverMSDDataset:
      mode: 'train'
      blur: 'Integer(10, 40)'
      nsamples: 128
  valid:
    LiverMSDDataset:
      mode: 'valid'
      nsamples: 256
  test:
    LiverMSDDataset:
      mode: 'test'
      nsamples: 256

model:
  ResNetSmall:
    base_size: 4608
    img_size: 100

transform:
        train: {}
        valid: {}
        test: {}
