base: "base_livermsd.yml"

model:
  ResNetModel:
    base_size: 4608
    resnet_type: "18"
    actdiff_lamb: 0
    gradmask_lamb: 0
    disc_lamb: "Real(10**-3, 10, 'log-uniform')"
    disc_iter: 'Integer(0, 10)'
    disc_lr: "Real(10**-4, 10**-2, 'log-uniform')"
    save_acts: [5]