# General
cuda: True
penalise_grad: 'False'
n_iter: 30
penalise_grad_lambda_1: 1.0
penalise_grad_lambda_2: 1.0
conditional_reg: False
penalise_grad_usemasks: True 
nsamples_train: 128
maxmasks_train: 128

# Training
num_epochs: 200

# DataLoader
batch_size: 32
shuffle: True

# Dataset
dataset:
  train:
    TNTDataset:
      mode: 'train'
      blur: 3
  valid:
    TNTDataset:
      mode: 'valid'
      nsamples: 512
      blur: 3
  test:
    TNTDataset:
      mode: 'test'
      nsamples: 512

# Model
model:
  SimpleCNN: 
    flat_layer: 2

# Optimizer
optimizer:
  Adam:
    lr: 0.00005

transform:
        train: {}
        valid: {}
        test: {}

