# General
cuda: True
penalise_grad: 'contrast'
n_iter: 30
penalise_grad_lambda_1: "Real(0., 5.)"
penalise_grad_lambda_2: "Real(0., 5.)"
conditional_reg: False
penalise_grad_usemasks: True 
nsamples_train: 128
maxmasks_train: 256
viz: False
new_size: &new_size 128

# Training
num_epochs: 100

# DataLoader
batch_size: "Integer(8, 64)"
shuffle: True

# Dataset
dataset:
  train:
    TNTDataset:
      mode: 'train'
      blur: "Integer(3, 7)"
      new_size: *new_size
  valid:
    TNTDataset:
      mode: 'valid'
      nsamples: 512
      new_size: *new_size
  test:
    TNTDataset:
      mode: 'test'
      nsamples: 512
      new_size: *new_size

# Model
model:
  SimpleCNN: 
    flat_layer: "Integer(1, 6)"
    img_size: *new_size

# Optimizer
optimizer:
  Adam:
    lr: "Real(10**-6, 10**-3, 'log-uniform')"
    weight_decay: "Real(10**-6, 10**-3, 'log-uniform')"

transform:
        train: {}
        valid: {}
        test: {}

