# General
cuda: True
penalise_grad: 'False'
n_iter: 30
penalise_grad_lambda_1: 1.0
penalise_grad_lambda_2: 1.0
conditional_reg: True
penalise_grad_usemasks: True 
nsamples_train: 128
maxmasks_train: 128

# Training
num_epochs: 200

# DataLoader
batch_size: 32
shuffle: True

# Dataset
dataset:
  train:
    HeartMSDDataset:
      mode: 'train'
      blur: 3
  valid:
    HeartMSDDataset:
      mode: 'valid'
      nsamples: 256
      blur: 3
  test:
    HeartMSDDataset:
      mode: 'test'
      nsamples: 256

# Model
model:
  SimpleCNN: 
    flat_layer: 2

# Optimizer
optimizer:
  Adam:
    lr: 0.0001

transform:
        train: {}
        valid: {}
        test: {}

