cuda: True
num_epochs: 100
schedule_steps: 10
batch_size: 32
shuffle: True

# Dataset
dataset:
  train:
    SyntheticDataset:
      mode: 'distractor1'
      blur: 7
      nsamples: 500
      new_size: *new_size
      dataroot: &dataroot './data/synth2/'
      distract_noise: 0
  valid:
    SyntheticDataset:
      mode: 'distractor2'
      blur: 7
      nsamples: 128
      new_size: *new_size
      dataroot: *dataroot
      distract_noise: 1
  test:
    SyntheticDataset:
      mode: 'distractor3'
      blur: 7
      nsamples: 128
      new_size: *new_size
      dataroot: *dataroot
      distract_noise: 1

transform:
        train: {}
        valid: {}
        test: {}
