# General
base: 'base_synth.yml'

# Model
model:
  ResNet:
    img_size: 28
    resnet_type: "18"
    actdiff_lamb: "Real(10**-3, 10, 'log-uniform')"
    gradmask_lamb: 0


# Optimizer
optimizer:
  Adam:
    lr: "Real(10**-4, 10**-2, 'log-uniform')"
