base: 'base_synth.yml'

dataset:
  train:
    SyntheticDataset:
        mask_all: True

model:
  ResNetModel:
    resnet_type: "18"
    actdiff_lamb: 0
    gradmask_lamb: 0
    disc_lamb: 0
    save_acts: []
