# General
base: "base_rsna.yml"

model:
  ResNetModel:
    actdiff_lamb: 0
    gradmask_lamb: 0
    disc_lamb: 10.0
    disc_iter: 10
    disc_lr: 0.000116
    save_acts: [5]

optimizer:
  Adam:
    lr: 0.000350
