base: "base_rsna_balanced.yml"

model:
  ResNetModel:
    actdiff_lamb: 0
    gradmask_lamb: 0
    disc_lamb: 0

optimizer:
  Adam:
    lr: 0.002841

dataset:
  train:
    XRayRSNADataset:
        mask_all: True
