# General
base: "base_xray.yml"

model:
  ResNetModel:
    resnet_type: "18"
    actdiff_lamb: 0
    gradmask_lamb: 0
    disc_lamb: 1
    disc_iter: 2
    disc_lr: 0.01
    save_acts: [5]


optimizer:
  Adam:
    lr: 0.000983
