base: "base_colonmsd.yml"

dataset:
  train:
    ColonMSDDataset:
      blur: 1.297616

model:
  ResNetModel:
    resnet_type: "18"
    actdiff_lamb: 0.000102
    gradmask_lamb: 0
    disc_lamb: 0
    save_acts: [5]

optimizer:
  Adam:
    lr: 0.000153
