base: "base_colonmsd.yml"

dataset:
  train:
    ColonMSDDataset:
      blur: 1.986998

model:
  ResNetModel:
    resnet_type: "18"
    actdiff_lamb: 0
    gradmask_lamb: 0.020014
    disc_lamb: 0
    save_acts: []

optimizer:
  Adam:
    lr: 0.000084
