base: "base_colonmsd.yml"

dataset:
  train:
    ColonMSDDataset:
      mask_all: True
      blur: 2.000000

model:
  ResNetModel:
    resnet_type: "18"
    actdiff_lamb: 0
    gradmask_lamb: 0
    disc_lamb: 0
    save_acts: []

optimizer:
  Adam:
    lr: 0.002911
