cuda: True
nsamples_train: 128
maxmasks_train: 256
recon_masked: False
recon_continuous: True
gradmask_lambda: 0
num_epochs: 100
schedule_steps: 10
batch_size: 32
shuffle: True

optimizer:
  Adam:
    lr: "Real(10**-5, 10**-2, 'log-uniform')"

dataset:
  train:
    HeartMSDDataset:
      mode: 'train'
      blur: 'Integer(10, 40)'
      nsamples: 128
  valid:
    HeartMSDDataset:
      mode: 'valid'
      nsamples: 256
  test:
    HeartMSDDataset:
      mode: 'test'
      nsamples: 256

model:
  ResNetSmall:
    base_size: 4608
    img_size: 100

transform:
        train: {}
        valid: {}
        test: {}
