batch_size: 32
n_iter: 50
n_initial_points: 5
n_epochs: 100
num_workers: 4
pin_memory: True
shuffle: True

dataset:
  train:
    HeartMSDDataset:
      base_path: '/srv/data/msd' 
      mode: 'train'
      blur: 'Integer(2, 20)'
      nsamples: 128
  valid:
    HeartMSDDataset:
      base_path: '/srv/data/msd'
      mode: 'valid'
      nsamples: 256
  test:
    HeartMSDDataset:
      base_path: '/srv/data/msd'
      mode: 'test'
      nsamples: 256

optimizer:
  Adam:
    lr: "Real(10**-5, 10**-2, 'log-uniform')"

transform:
        train: {}
        valid: {}
        test: {}
