device: 0
cuda: True
num_epochs: 500
schedule_steps: 10
batch_size: 32
shuffle: True
new_size: &new_size 28
num_workers: 4
pin_memory: True

dataset:
  train:
    HeartMSDDataset:
      mode: 'train'
      blur: 'Integer(2, 40)'
      nsamples: 128
  valid:
    HeartMSDDataset:
      mode: 'valid'
      nsamples: 256
  test:
    HeartMSDDataset:
      mode: 'test'
      nsamples: 256

optimizer:
  Adam:
    lr: "Real(10**-5, 10**-2, 'log-uniform')"

transform:
        train: {}
        valid: {}
        test: {}
