batch_size: 32
cuda: True
device: 0
gradmask_lambda: 0
maxmasks_train: 256
new_size: &new_size 28
nsamples_train: 128
n_iter: 30
num_epochs: 500
num_workers: 4
pin_memory: True
recon_continuous: True
recon_masked: False
schedule_steps: 10
shuffle: True

dataset:
  train:
    HeartMSDDataset:
      mode: 'train'
      blur: 'Integer(2, 40)'
      nsamples: 128
  valid:
    HeartMSDDataset:
      mode: 'valid'
      nsamples: 256
  test:
    HeartMSDDataset:
      mode: 'test'
      nsamples: 256

optimizer:
  Adam:
    lr: "Real(10**-5, 10**-2, 'log-uniform')"

transform:
        train: {}
        valid: {}
        test: {}
