# General
base: "base_cardiacmsd.yml"
bre_lambda: 0
recon_lambda: 0
actdiff_lambda: 1

dataset:
  train:
    HeartMSDDataset:
      blur: 4

# Model
model:
  ResNetSmall:
    base_size: 4608
    img_size: 100

