# General
base: "base_xray_balanced.yml"

model:
  ResNetModel:
    resnet_type: "18"
    actdiff_lamb: 10
    gradmask_lamb: 0
    disc_lamb: 0
    save_acts: [5]


optimizer:
  Adam:
    lr: 0.008917
