# General
base: "base_xray.yml"

model:
  ResNetModel:
    resnet_type: "18"
    actdiff_lamb: 0
    gradmask_lamb: 0
    disc_lamb: 0
    save_acts: []

dataset:
  train:
    XRayDataset:
        mask_all: True

        
optimizer:
  Adam:
    lr: 0.01
