# General
base: "base_xray_balanced.yml"

model:
  ResNetModel:
    resnet_type: "18"
    actdiff_lamb: 0
    gradmask_lamb: 0
    rrr_lamb: 10.000000 
    disc_lamb: 0
    save_acts: []


optimizer:
  Adam:
    lr: 0.001393
