# General
base: "base_xray_balanced.yml"

model:
  ResNetModel:
    resnet_type: "18"
    actdiff_lamb: 0
    gradmask_lamb: 0.097965
    disc_lamb: 0
    save_acts: []


optimizer:
  Adam:
    lr: 0.010000
