# General
cuda: True
n_iter: 200
nsamples_train: 500
maxmasks_train: 256
new_size: &new_size 28
recon_masked: False
recon_continuous: False
gradmask_lambda: 0

# Training
num_epochs: 500
schedule_steps: 10

# DataLoader
batch_size: 32
shuffle: True

# Dataset
dataset:
  train:
    XRayDataset:
      d1data: "/lustre03/project/6008064/jpcohen/ChestXray-NIHCC"
      d1csv: "/lustre03/project/6008064/jpcohen/ChestXray-NIHCC/Data_Entry_2017.csv"
      d2data: "/lustre03/project/6008064/jpcohen/PADCHEST_SJ/"
      d2csv: "/lustre03/project/6008064/jpcohen/PADCHEST_SJ/labels_csv/PADCHEST_chest_x_ray_images_labels_160K_01.02.19.csv"
      mode: 'distractor1'
      ratio: 0.75
      mode: "train"
  valid:
    XRayDataset:
      d1data: "/lustre03/project/6008064/jpcohen/ChestXray-NIHCC"
      d1csv: "/lustre03/project/6008064/jpcohen/ChestXray-NIHCC/Data_Entry_2017.csv"
      d2data: "/lustre03/project/6008064/jpcohen/PADCHEST_SJ/"
      d2csv: "/lustre03/project/6008064/jpcohen/PADCHEST_SJ/labels_csv/PADCHEST_chest_x_ray_images_labels_160K_01.02.19.csv"
      mode: 'distractor1'
      ratio: 0.25
      mode: "valid"
  test:
    XRayDataset:
      d1data: "/lustre03/project/6008064/jpcohen/ChestXray-NIHCC"
      d1csv: "/lustre03/project/6008064/jpcohen/ChestXray-NIHCC/Data_Entry_2017.csv"
      d2data: "/lustre03/project/6008064/jpcohen/PADCHEST_SJ/"
      d2csv: "/lustre03/project/6008064/jpcohen/PADCHEST_SJ/labels_csv/PADCHEST_chest_x_ray_images_labels_160K_01.02.19.csv"
      mode: 'distractor1'
      ratio: 0.5
      mode: "test"

# Optimizer
optimizer:
  Adam:
    lr:  0.0001

transform:
        train: {}
        valid: {}
        test: {}
