# General
base: "base_xray.yml"
bre_lambda: 0
recon_lambda: 0
actdiff_lambda: 0
gradmask_lambda: 0

dataset:
  train:
    XRayDataset:
        mask_all: True
dataset:
  valid:
    XRayDataset:
        mask_all: True
dataset:
  test:
    XRayDataset:
        mask_all: True
