device: 0
cuda: True
nsamples_train: 128
maxmasks_train: 256
recon_masked: False
recon_continuous: True
gradmask_lambda: 0
n_iter: 30
num_epochs: 500
schedule_steps: 10
batch_size: 32
shuffle: True
num_workers: 0
pin_memory: True

# Dataset
dataset:
  train:
    PancreasMSDDataset:
      mode: 'train'
      blur: 16
      nsamples: 128
  valid:
    PancreasMSDDataset:
      mode: 'valid'
      nsamples: 256
  test:
    PancreasMSDDataset:
      mode: 'test'
      nsamples: 256

# Optimizer
optimizer:
  Adam:
    lr: 0.0001

transform:
        train: {}
        valid: {}
        test: {}
