batch_size: 32
n_epochs: 100
num_workers: 0
pin_memory: True
shuffle: True

# Dataset
dataset:
  train:
    PancreasMSDDataset:
      mode: 'train'
      blur: 16
      nsamples: 128
  valid:
    PancreasMSDDataset:
      mode: 'valid'
      nsamples: 256
  test:
    PancreasMSDDataset:
      mode: 'test'
      nsamples: 256

# Optimizer
optimizer:
  Adam:
    lr: 0.0001

transform:
        train: {}
        valid: {}
        test: {}
