batch_size: 32
cuda: True
device: 0
gradmask_lambda: 0
n_iter: 30
nsamples_train: 500
n_epochs: 100
num_workers: 0
pin_memory: True
recon_continuous: False
recon_masked: False
schedule_steps: 10
shuffle: True

# Dataset
dataset:
  train:
    SyntheticDataset:
      mode: 'distractor1'
      blur: 3
      nsamples: 500
      dataroot: &dataroot "/home/jdv/code/activmask/data/synth2"
      distract_noise: 0
  valid:
    SyntheticDataset:
      mode: 'distractor2'
      blur: 3
      nsamples: 128
      dataroot: *dataroot
      distract_noise: 1
  test:
    SyntheticDataset:
      mode: 'distractor3'
      blur: 3
      nsamples: 128
      dataroot: *dataroot
      distract_noise: 1

# Optimizer
optimizer:
  Adam:
    lr:  0.0001

transform:
        train: {}
        valid: {}
        test: {}
