device: 0
cuda: True
num_epochs: 500
schedule_steps: 10
batch_size: 32
shuffle: True
new_size: &new_size 28
num_workers: 4
pin_memory: True

# Dataset
dataset:
  train:
    SyntheticDataset:
      mode: 'distractor1'
      blur: 3
      nsamples: 500
      new_size: &new_size 28
      dataroot: &dataroot "/home/jdv/code/activmask/data/synth2"
      distract_noise: 0
  valid:
    SyntheticDataset:
      mode: 'distractor2'
      blur: 3
      nsamples: 128
      new_size: *new_size
      dataroot: *dataroot
      distract_noise: 1
  test:
    SyntheticDataset:
      mode: 'distractor3'
      blur: 3
      nsamples: 128
      new_size: *new_size
      dataroot: *dataroot
      distract_noise: 1

# Optimizer
optimizer:
  Adam:
    lr:  0.0001

transform:
        train: {}
        valid: {}
        test: {}
