# General
base: 'base_synth.yml'

# Model
model:
  ResNetModel:
    resnet_type: "18"
    actdiff_lamb: 0
    gradmask_lamb: 0
    disc_lamb: 10
    disc_iter: 5
    disc_lr: 0.001
    save_acts: [5]
