batch_size: 32
n_epochs: 500
n_initial_points: 5
n_iter: 50
num_workers: 8
patience: 20
pin_memory: True
shuffle: True

dataset:
  train:
    PancreasMSDDataset:
      base_path: '/srv/data/msd'
      mode: 'train'
      blur: 'Real(0, 5)'
      nsamples: 128
  valid:
    PancreasMSDDataset:
      base_path: '/srv/data/msd'
      mode: 'valid'
      nsamples: 256
  test:
    PancreasMSDDataset:
      base_path: '/srv/data/msd'
      mode: 'test'
      nsamples: 256

optimizer:
  Adam:
    lr: "Real(10**-5, 10**-2, 'log-uniform')"

transform:
        train: {}
        valid: {}
        test: {}
