batch_size: 32
n_iter: 30
n_epochs: 100
num_workers: 0
pin_memory: True
shuffle: True


dataset:
  train:
    PancreasMSDDataset:
      mode: 'train'
      blur: 'Integer(2, 40)'
      nsamples: 128
  valid:
    PancreasMSDDataset:
      mode: 'valid'
      nsamples: 256
  test:
    PancreasMSDDataset:
      mode: 'test'
      nsamples: 256

optimizer:
  Adam:
    lr: "Real(10**-4, 10**-2, 'log-uniform')"

transform:
        train: {}
        valid: {}
        test: {}
