cuda: True
num_epochs: 500
schedule_steps: 10
batch_size: 32
shuffle: True

dataset:
  train:
    PancreasMSDDataset:
      mode: 'train'
      blur: 'Integer(2, 40)'
      nsamples: 128
  valid:
    PancreasMSDDataset:
      mode: 'valid'
      nsamples: 256
  test:
    PancreasMSDDataset:
      mode: 'test'
      nsamples: 256

model:
  ResNetSmall:
    base_size: 4608
    img_size: 100

transform:
        train: {}
        valid: {}
        test: {}
