# General
base: "base_pancreasmsd.yml"
bre_lambda: 0
recon_lambda: 0
actdiff_lambda: 0
num_epochs: 100

# Model
model:
  ResNetSmall:
    base_size: 4608
    img_size: 100

optimizer:
  Adam:
    lr: "Real(10**-4, 10**-2, 'log-uniform')"

