# General
base: "base_pancreasmsd.yml"
bre_lambda: 0
recon_lambda: 0
actdiff_lambda: 0

# Model
model:
  ResNetSmall:
    base_size: 4608
    img_size: 100

dataset:
  train:
    PancreasMSDDataset:
      blur: "Int(10, 40)"
      mask_all: True

# Optimizer
optimizer:
  Adam:
    lr: "Real(10**-5, 10**-2, 'log-uniform')"
