base: "base_livermsd.yml"

dataset:
  train:
    LiverMSDDataset:
      blur: 0.000000

model:
  ResNetModel:
    resnet_type: "18"
    actdiff_lamb: 0.000100   
    gradmask_lamb: 0
    disc_lamb: 0
    save_acts: [5]

optimizer:
  Adam:
    lr: 0.000894

