base: "base_livermsd.yml"

dataset:
  train:
    LiverMSDDataset:
      blur: 10

model:
  ResNetModel:
    resnet_type: "18"
    actdiff_lamb: 0
    gradmask_lamb: 0
    disc_lamb: 0.010000
    disc_iter: 2
    disc_lr: 0.000100
    save_acts: [5]

optimizer:
  Adam:
    lr: 0.000486

