base: "base_livermsd.yml"

dataset:
  train:
    LiverMSDDataset:
      blur: 20

model:
  ResNetModel:
    resnet_type: "18"
    actdiff_lamb: 0
    gradmask_lamb: 0.000100
    disc_lamb: 0
    save_acts: []

optimizer:
  Adam:
    lr: 0.000115