base: "base_livermsd.yml"

dataset:
  train:
    LiverMSDDataset:
      blur: 1.337767

model:
  ResNetModel:
    resnet_type: "18"
    actdiff_lamb: 0
    gradmask_lamb: 0
    disc_lamb: 0
    save_acts: []
    #base_size: 4608

optimizer:
  Adam:
    lr: 0.000596

