# General
cuda: True
n_iter: 30
nsamples_train: 64
maxmasks_train: 256
recon_masked: False
recon_continuous: True
gradmask_lambda: 0

# Training
num_epochs: 100
schedule_steps: 10

# DataLoader
batch_size: 32
shuffle: True

# Dataset
dataset:
  train:
    LiverMSDDataset:
      mode: 'train'
      blur: "Integer(1, 5)"
  valid:
    LiverMSDDataset:
      mode: 'valid'
      nsamples: 256
  test:
    LiverMSDDataset:
      mode: 'test'
      nsamples: 256

# Optimizer
optimizer:
  Adam:
    lr: "Real(10**-6, 10**-2, 'log-uniform')"

transform:
        train: {}
        valid: {}
        test: {}
