# General
base: "base_livermsd.yml"
bre_lambda: 0
recon_lambda: 0
actdiff_lambda: "Real(10**-4, 10**-1, 'log-uniform')"

# Model
model:
  ResNetSmall:
    base_size: 4608
    img_size: 100

# Optimizer
optimizer:
  Adam:
    lr: "Real(10**-4, 10**-2, 'log-uniform')"