# General
base: "base_livermsd.yml"
bre_lambda: 0
recon_lambda: 0
actdiff_lambda: 0

# Model
model:
  UNet:
    img_size: 100
    nc: 64
    mode: 'cnn'
    normrecon: False

dataset:
  train:
    LiverMSDDataset:
        mask_all: True

