device: 0
cuda: True
num_epochs: 500
schedule_steps: 10
batch_size: 32
shuffle: True
num_workers: 0
pin_memory: True

# Dataset
dataset:
  train:
    HeartMSDDataset:
      mode: 'train'
      blur: 8
      nsamples: 128
  valid:
    HeartMSDDataset:
      mode: 'valid'
      nsamples: 256
  test:
    HeartMSDDataset:
      mode: 'test'
      nsamples: 256

# Optimizer
optimizer:
  Adam:
    lr: 0.004

transform:
        train: {}
        valid: {}
        test: {}
