batch_size: 32
n_epochs: 100
num_workers: 8
patience: 20
pin_memory: True
shuffle: True

dataset:
  train:
    HeartMSDDataset:
      mode: 'train'
      blur: 8
      nsamples: 128
  valid:
    HeartMSDDataset:
      mode: 'valid'
      nsamples: 256
  test:
    HeartMSDDataset:
      mode: 'test'
      nsamples: 256

# Optimizer
optimizer:
  Adam:
    lr: 0.004

transform:
        train: {}
        valid: {}
        test: {}
