# General
base: "base_livermsd.yml"
bre_lambda: 0
recon_lambda: 1
actdiff_lambda: 1

# Model
model:
  UNet:
    img_size: 100
    nc: 64
    mode: 'unet'

# mlflow experiment manager
#manager:
#    set_experiment:
#        name: 'livermsd_resnet_actdiff_skopt' # Experience name
#    set_tracking_uri:
#        uri: '' # Link or url to where to store the logs. Default is `./mlruns`
