# General
base: "base_livermsd.yml"
bre_lambda: 0
recon_lambda: 0
actdiff_lambda: 0

# Model
model:
  ResNetSmall:
    base_size: 4608
    img_size: 100

# mlflow experiment manager
#manager:
#    set_experiment:
#        name: 'livermsd_resnet_actdiff_skopt' # Experience name
#    set_tracking_uri:
#        uri: '' # Link or url to where to store the logs. Default is `./mlruns`
